### PR TITLE
Feat: Fetching available theaters with escape game

### PR DESCRIPTION
**Pull request by massdx**
# Fetching available theaters with escape game

## Description

Added getAllEscapeGames method in theaters controller to fetch all available theaters with escape game.
Created /escape-game route in theaters route.
Added theaters-escape-game.model.ts in models.
tested the end-point

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by NemesisX1 — CHANGES_REQUESTED** [review]
Please, can you add tests in the scrapping-service.test.ts file about the new scrapping function you added in the ScrappingService ?

I will be really cool too if you can add docs in its related route

**Comment by massdx** [comment]
I'm not doing too well with Swager's doc but he'll try

**Comment by NemesisX1** [comment]
> I'm not doing too well with Swager's doc but he'll try

The swagger docs is not a requirement don't worry. But if you wanna do it you can have a look at this one https://swagger-autogen.github.io/docs/

**Review by NemesisX1 — APPROVED** [review]

**Comment by massdx** [comment]
ok thanks i will do it

**Comment by NemesisX1** [comment]
@massdx I've made some refactoring directly in the main branch. You can get a look at it. I also added docs and English language support

**Pull request merged**
